name: Dispatch workflows
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 7 * * *' #7am every day
jobs:
  dispatch_workflows:
    name: Dispatch workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Auth token for launching workflows
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.AUTOMATIC_WORKFLOW_DISPATCHER_APP_KEY }}
          app-id: ${{ secrets.AUTOMATIC_WORKFLOW_DISPATCHER_APP_ID }}

      - name: Dispatch workflows
        shell: bash
        run: docker run -e GITHUB_TOKEN -e DRYRUN=true -v "$(realpath output):/output" artifactory.algol60.net/csm-docker/unstable/hms-build-workflow-dispatcher:1.1.0-20220706022822.0b0e5a9
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.5
        with:
          # It is expected the that the build-image-comment-template.md is present in the application repo, not this one.
          template: .github/dispatch_workflows_summary_template.md.tpl
          vars_path: ./output/job_summary_template_values.yaml

      - name: Job Summary
        run: echo '${{ steps.template.outputs.result }}'