name: Dispatch workflows
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 7 * * *' #7am every day
jobs:
  dispatch_workflows:
    strategy:
      matrix:
        product-stream: ["csm", "spc"]
      fail-fast: false
    name: Dispatch workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        shell: bash
        run: pip3 install -r requirements.txt        
      
      - name: Auth token for launching workflows
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.AUTOMATIC_WORKFLOW_DISPATCHER_APP_KEY }}
          app-id: ${{ secrets.AUTOMATIC_WORKFLOW_DISPATCHER_APP_ID }}

      - name: Dispatch workflows
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
          ARTIFACTORY_ALGOL60_READONLY_USERNAME: ${{ secrets.ARTIFACTORY_ALGOL60_READONLY_USERNAME }}
          ARTIFACTORY_ALGOL60_READONLY_TOKEN: ${{ secrets.ARTIFACTORY_ALGOL60_READONLY_TOKEN }}
          DISPATCHER_CONFIGURATION_FILE: configuration_${{ matrix.product-stream }}.yaml
          DRYRUN: true
        run: ./dispatcher.py

      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.5
        with:
          # It is expected the that the dispatch_workflows_summary_template.md.tpl is present in this repo.
          template: .github/dispatch_workflows_summary_template.md.tpl
          vars_path: ./output/job_summary_template_values.yaml

      - name: Job Summary
        run: echo '${{ steps.template.outputs.result }}' >> $GITHUB_STEP_SUMMARY