name: Dispatch workflows
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 7 * * *' #7am every day
jobs:
  dispatch_workflows:
    name: Dispatch workflows
    runs-on: ubuntu-latest
    steps:
      - name: Auth token for PR creation
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.AUTOMATIC_WORKFLOW_DISPATCHER_APP_KEY }}
          app-id: ${{ secrets.AUTOMATIC_WORKFLOW_DISPATCHER_APP_ID }}

      - name: Dispatch workflows
        shell: bash
        run: docker run -e GITHUB_TOKEN artifactory.algol60.net/csm-docker/stable/hms-build-workflow-dispatcher:1.0.0
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}


